services:
  imsda-registration:
    build:
      context: ./pwa-server
      dockerfile: Dockerfile
    container_name: imsda-registration
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    env_file: ./pwa-server/.env
