<?php
if (!defined('ABSPATH')) { exit; }
class IMSDA_Reg_Admin {
    public static function init(){ add_action('admin_menu',[__CLASS__,'menu']); add_action('admin_init',[__CLASS__,'select_event']); }
    public static function menu(){ add_menu_page('IMSDA Reg','IMSDA Reg','manage_options','imsda-reg-dashboard',[__CLASS__,'dashboard'],'dashicons-groups',30); $subs=['events'=>'Events','registrations'=>'Registrations','waitlist'=>'Waitlist','checkin'=>'Check-In','rosters'=>'Church Rosters','promo'=>'Promo Codes','settings'=>'Settings']; foreach($subs as $k=>$label){ add_submenu_page('imsda-reg-dashboard',$label,$label,'manage_options','imsda-reg-'.$k,[__CLASS__,'page']); }}
    public static function select_event(){ if(isset($_POST['imsda_selected_event'])) update_user_meta(get_current_user_id(),'imsda_reg_selected_event',sanitize_key($_POST['imsda_selected_event'])); }
    private static function selected_slug(){ return sanitize_key(get_user_meta(get_current_user_id(),'imsda_reg_selected_event',true)); }
    private static function event_switcher(){ $events=IMSDA_Reg_Event_Registry::get_all(); $active=array_filter($events,fn($e)=>($e['status']??'')==='active'); if(!$active){ echo '<div class="notice notice-warning"><p>No events configured. Go to Events to add your first event.</p></div>'; return; } echo '<form method="post"><select name="imsda_selected_event">'; foreach($active as $slug=>$e){ echo '<option value="'.esc_attr($slug).'" '.selected(self::selected_slug(),$slug,false).'>'.esc_html($e['name']).'</option>'; } echo '</select> <button class="button">Switch</button></form>'; }
    public static function dashboard(){ $q=IMSDA_Reg_Queue::get_queue(); $f=IMSDA_Reg_Queue::get_failed(); echo '<div class="wrap"><h1>IMSDA Reg Dashboard</h1><h2>Global Queue Status</h2><p>Total Queued: '.count($q).' | Total Failed: '.count($f).'</p></div>'; }
    public static function page(){ $page=sanitize_key($_GET['page']??''); echo '<div class="wrap"><h1>'.esc_html(ucwords(str_replace('imsda-reg-','',$page))).'</h1>'; if(!in_array($page,['imsda-reg-dashboard','imsda-reg-events'],true)) self::event_switcher(); if($page==='imsda-reg-events') self::events_page(); else echo '<p>Use AJAX actions on this page to load/manage data for selected event.</p>'; echo '</div>'; }
    private static function events_page(){ $events=IMSDA_Reg_Event_Registry::get_all(); echo '<p>Add, edit, import, and export event profiles from here.</p><table class="widefat"><tr><th>Name</th><th>Slug</th><th>Dates</th><th>Form ID</th><th>Capacity</th><th>Status</th></tr>'; foreach($events as $e){ echo '<tr><td>'.esc_html($e['name']).'</td><td>'.esc_html($e['slug']).'</td><td>'.esc_html($e['dates']).'</td><td>'.intval($e['form_id']).'</td><td>'.intval($e['capacity']).'</td><td>'.esc_html($e['status']).'</td></tr>'; } echo '</table>'; }
}
