<?php
if (!defined('ABSPATH')) { exit; }
class IMSDA_Reg_Shortcodes {
    public static function init(){ add_shortcode('imsda_availability',[__CLASS__,'availability']); add_shortcode('imsda_availability_banner',[__CLASS__,'availability_banner']); add_shortcode('imsda_edit_registration',[__CLASS__,'edit_registration']); }
    private static function load_event($atts){ $a=shortcode_atts(['event'=>''],$atts); $e=IMSDA_Reg_Event_Registry::get($a['event']); if(!$e || $e->status!=='active') return null; return $e; }
    public static function availability($atts){ $e=self::load_event($atts); if(!$e) return 'Registration closed'; ob_start(); ?><div class="imsda-availability" data-event="<?php echo esc_attr($e->slug); ?>">Loading availability...</div><script>jQuery(function($){function load(){ $.post('<?php echo esc_js(admin_url('admin-ajax.php')); ?>',{action:'imsda_reg_get_availability',event_slug:'<?php echo esc_js($e->slug); ?>'},function(r){$('.imsda-availability[data-event="<?php echo esc_js($e->slug); ?>"]').text(JSON.stringify(r));}); } load(); setInterval(load,60000);});</script><?php return ob_get_clean(); }
    public static function availability_banner($atts){ return '<div class="imsda-availability-banner">'.self::availability($atts).'</div>'; }
    public static function edit_registration($atts){ $e=self::load_event($atts); if(!$e) return 'Registration closed'; $token=sanitize_text_field($_GET['token']??''); if(!$token) return 'Missing token.'; ob_start(); ?><form id="imsda-edit-form"><input type="hidden" name="edit_token" value="<?php echo esc_attr($token); ?>"/><input name="first_name" placeholder="First Name"><input name="last_name" placeholder="Last Name"><input name="phone" placeholder="Phone"><button type="submit">Save</button></form><div id="imsda-edit-msg"></div><script>jQuery(function($){$.post('<?php echo esc_js(admin_url('admin-ajax.php')); ?>',{action:'imsda_reg_get_reg_by_token',event_slug:'<?php echo esc_js($e->slug); ?>',token:'<?php echo esc_js($token); ?>'},function(r){if(r&&r.data){for(const k in r.data){$('#imsda-edit-form [name="'+k+'"]').val(r.data[k]);}}});$('#imsda-edit-form').on('submit',function(ev){ev.preventDefault();var d=$(this).serializeArray();d.push({name:'action',value:'imsda_reg_save_edit'},{name:'event_slug',value:'<?php echo esc_js($e->slug); ?>'});$.post('<?php echo esc_js(admin_url('admin-ajax.php')); ?>',d,function(r){$('#imsda-edit-msg').text(r.success?'Saved':'Error'); if(r.success) $('#imsda-edit-form').hide();});});});</script><p>To change email or payment details, contact us.</p><?php return ob_get_clean(); }
}
