<?php
if (!defined('ABSPATH')) { exit; }
class IMSDA_Reg_Admin {
    public static function init(){ add_action('admin_menu',[__CLASS__,'menu']); add_action('admin_init',[__CLASS__,'select_event']); }
    public static function menu(){ add_menu_page('IMSDA Reg','IMSDA Reg','manage_options','imsda-reg-dashboard',[__CLASS__,'dashboard'],'dashicons-groups',30); $subs=['events'=>'Events','registrations'=>'Registrations','waitlist'=>'Waitlist','checkin'=>'Check-In','rosters'=>'Church Rosters','promo'=>'Promo Codes','settings'=>'Settings']; foreach($subs as $k=>$label){ add_submenu_page('imsda-reg-dashboard',$label,$label,'manage_options','imsda-reg-'.$k,[__CLASS__,'page']); }}
    public static function select_event(){ if(isset($_POST['imsda_selected_event'])) update_user_meta(get_current_user_id(),'imsda_reg_selected_event',sanitize_key($_POST['imsda_selected_event'])); }
    private static function selected_slug(){ return sanitize_key(get_user_meta(get_current_user_id(),'imsda_reg_selected_event',true)); }
    private static function nonce(){ return wp_create_nonce('imsda_reg_admin_nonce'); }
    private static function event_switcher(){ $events=IMSDA_Reg_Event_Registry::get_all(); if(!$events){ echo '<div class="notice notice-warning"><p>No events configured. Go to Events to add your first event.</p></div>'; return; } echo '<form method="post" style="margin:8px 0 16px;"><select name="imsda_selected_event">'; foreach($events as $slug=>$e){ echo '<option value="'.esc_attr($slug).'" '.selected(self::selected_slug(),$slug,false).'>'.esc_html($e['name']).' ('.esc_html($slug).')</option>'; } echo '</select> <button class="button">Switch</button></form>'; }

    public static function dashboard(){ self::render_shell('imsda-reg-dashboard'); }
    public static function page(){ self::render_shell(sanitize_key($_GET['page']??'')); }

    private static function render_shell($page){
        $events=IMSDA_Reg_Event_Registry::get_all(); $selected=self::selected_slug(); if(!$selected && $events) $selected=array_key_first($events);
        echo '<div class="wrap"><h1>IMSDA Registration Engine</h1>';
        if(!in_array($page,['imsda-reg-dashboard','imsda-reg-events','imsda-reg-settings'],true)) self::event_switcher();
        if($page==='imsda-reg-settings'){ self::settings_page(); echo '</div>'; return; }
        echo '<div id="imsda-admin-app" data-page="'.esc_attr($page).'" data-selected="'.esc_attr($selected).'" data-nonce="'.esc_attr(self::nonce()).'" data-events="'.esc_attr(wp_json_encode($events)).'"></div>';
        self::assets();
        echo '</div>';
    }

    private static function settings_page(){ if(isset($_POST['imsda_reg_save_settings']) && check_admin_referer('imsda_reg_save_settings')){ $s=['admin_email'=>sanitize_email($_POST['admin_email']??''),'queue_max_attempts'=>max(1,intval($_POST['queue_max_attempts']??5))]; update_option('imsda_reg_global_settings',$s,false); if(!empty($_POST['clear_queue'])) update_option('imsda_reg_dispatch_queue',[],false); if(!empty($_POST['clear_failed'])) update_option('imsda_reg_failed_submissions',[],false); echo '<div class="updated"><p>Settings saved.</p></div>'; }
        $s=get_option('imsda_reg_global_settings',[]); $next=wp_next_scheduled('imsda_reg_process_queue');
        echo '<form method="post">'; wp_nonce_field('imsda_reg_save_settings'); echo '<table class="form-table"><tr><th>Admin Notification Email</th><td><input type="email" name="admin_email" value="'.esc_attr($s['admin_email']??'').'"></td></tr><tr><th>Queue Max Attempts</th><td><input type="number" min="1" name="queue_max_attempts" value="'.intval($s['queue_max_attempts']??5).'"></td></tr><tr><th>Cron next run</th><td><input readonly value="'.esc_attr($next?wp_date('Y-m-d H:i:s',$next):'Not scheduled').'" class="regular-text"></td></tr></table><div style="border:2px solid #b32d2e;padding:12px;margin:12px 0;"><h3 style="color:#b32d2e">Danger Zone</h3><label><input type="checkbox" name="clear_queue" value="1"> Clear Entire Queue</label><br><label><input type="checkbox" name="clear_failed" value="1"> Clear All Failed Submissions</label></div><p><button class="button button-primary" name="imsda_reg_save_settings" value="1">Save Settings</button></p></form>';
    }

    private static function assets(){ ?>
<style>.ims-tabs button{margin-right:6px}.ims-tab{display:none}.ims-tab.active{display:block}.ims-modal{position:fixed;z-index:100000;inset:0;background:rgba(0,0,0,.45);display:none;align-items:center;justify-content:center}.ims-modal .box{background:#fff;padding:16px;max-width:900px;width:95%;max-height:90vh;overflow:auto}.badge{padding:2px 8px;border-radius:999px;color:#fff}.b-active{background:#008a20}.b-inactive{background:#666}.b-closed{background:#b32d2e}.prog{height:10px;background:#eee;border-radius:6px}.prog i{display:block;height:100%;border-radius:6px}</style>
<script>
jQuery(function($){const app=$('#imsda-admin-app'); if(!app.length)return; const nonce=app.data('nonce'),page=app.data('page'),events=JSON.parse(app.attr('data-events')||'{}'); let slug=app.data('selected')||''; const ajax=(a,d,ok)=>$.post(ajaxurl,Object.assign({action:'imsda_reg_admin_action',nonce:nonce,imsda_action:a,event_slug:slug},d||{}),ok);
function status(s){return '<span class="badge b-'+s+'">'+s+'</span>'}
function payCell(r){return (r.paymentStatus||'')+' '+(r.finalAmount?('$'+r.finalAmount):'')}
function paymentPanel(id,b){return `<div><p>Method <select class='pm'><option>cash</option><option>check</option><option>square</option><option>other</option></select> Amount <input class='amt' value='${b||0}' type='number' step='0.01'> <button class='button savepay' data-id='${id}'>Save</button></p><p class='checkrow' style='display:none'>Check # <input class='chk'></p><div class='sq' style='display:none'>Square calc <select class='sqtype'><option value='0.026,0.10'>Tap/Chip/Swipe</option><option value='0.035,0.15'>Manual Key Entry</option></select> <b class='sqamt'></b> <button class='button copyamt'>Copy</button></div><textarea class='notes' placeholder='Notes'></textarea></div>`;}
function renderEvents(){const dfm=<?php echo wp_json_encode(IMSDA_Reg_Event_Registry::default_field_map());?>; let rows=''; Object.values(events).forEach(e=>{const reg=e.slug?<?php echo '0'; ?>:0; rows+=`<tr><td>${e.name||''}</td><td>${e.slug||''}</td><td>${e.dates||''}</td><td>${e.form_id||''}</td><td>${e.status||''}</td><td>${(e.registered_count||0)}/${e.capacity||0}</td><td><a href='#' class='edit' data-slug='${e.slug}'>Edit</a> | <a href='#' class='exp' data-slug='${e.slug}'>Export</a> | <a href='#' class='del' data-slug='${e.slug}'>Delete</a></td></tr>`});
app.html(`<p><button class='button button-primary' id='add'>Add New Event</button> <button class='button' id='imp'>Import Event</button></p><table class='widefat'><tr><th>Name</th><th>Slug</th><th>Dates</th><th>Form ID</th><th>Status</th><th>Registered/Cap</th><th>Actions</th></tr>${rows}</table><div id='importP' style='display:none;margin-top:12px;border:1px solid #ccc;padding:10px'><div style='display:flex;gap:16px'><div><input type='file' id='ifile' accept='.json'></div><div><textarea id='ijson' rows='8' cols='50' placeholder='Paste JSON'></textarea></div></div><p><button class='button button-primary' id='doimp'>Import</button> <span id='imsg'></span></p></div><div id='formWrap'></div>`);
$('#imp').click(()=>$('#importP').toggle());
app.on('click','.del',function(e){e.preventDefault();if(confirm('Delete this event?')){slug=$(this).data('slug');ajax('deleteEvent',{},()=>location.reload());}});
app.on('click','.exp',function(e){e.preventDefault();slug=$(this).data('slug');ajax('exportEvent',{},res=>{if(res.success){const b=new Blob([res.data.json],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=slug+'-event-profile.json';a.click();}})});
$('#doimp').click(()=>{const f=$('#ifile')[0].files[0],txt=$('#ijson').val(); if(!f&&!txt){$('#imsg').text('Provide file or JSON');return;} const fd=new FormData(); fd.append('action','imsda_reg_admin_action'); fd.append('nonce',nonce); fd.append('imsda_action','importEvent'); fd.append('event_slug',slug); if(f)fd.append('event_file',f); fd.append('event_json',txt); $.ajax({url:ajaxurl,type:'POST',data:fd,processData:false,contentType:false,success:r=>{if(r.success){$('#imsg').html(`<div style='background:#fff8e5;border:1px solid #dba617;padding:8px'>⚠ Copy this secret into your GAS Config sheet now. It will not be shown again in full.<br><code>${r.data.gas_secret}</code> <button class='button copysec'>Copy</button></div>`); location.reload();} else $('#imsg').text(r.data.message||'Error');}})});
}
function renderDashboard(){ajax('runQueue',{},()=>{});app.html('<div id="dash"></div>');}
function renderGeneric(action,cols,rowFn,actions=''){app.html(`<p><input id='s'> <button class='button r'>Refresh</button></p><table class='widefat'><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody id='tb'></tbody></table><div class='ims-modal' id='m'><div class='box'></div></div>`); const load=()=>ajax(action,{q:$('#s').val(),status:$('#status').val()},r=>{$('#tb').html((r.data?.rows||r.data||[]).map(rowFn).join(''))}); load(); app.on('click','.r',load);}
if(page==='imsda-reg-events') renderEvents();
if(page==='imsda-reg-registrations') renderGeneric('getRegistrations',['ID','Name','Church','Payment','Status','Checked In','Actions'],r=>`<tr><td>${r.id}</td><td>${r.firstName||''} ${r.lastName||''}<br><small>${r.email||''}</small></td><td>${r.church||''}</td><td>${payCell(r)}</td><td>${r.status||''}</td><td>${r.checkedIn?'Yes':'No'}</td><td><button class='button e' data-id='${r.id}'>Edit</button> <button class='button t' data-id='${r.id}'>Transfer</button> ${( ['pending_check','pending_pay_later','unpaid'].includes(r.paymentStatus)?`<button class='button p' data-id='${r.id}' data-bal='${r.finalAmount||0}'>Record Payment</button>`:'')}</td></tr>`);
if(page==='imsda-reg-waitlist') renderGeneric('getWaitlist',['Position','Name','Email','Church','Date Added','Status','Actions'],r=>`<tr><td>${r.position||''}</td><td>${r.name||''}</td><td>${r.email||''}</td><td>${r.church||''}</td><td>${r.dateAdded||''}</td><td>${r.status||''}</td><td><button class='button promote' data-id='${r.id}'>Promote</button> <button class='button remove' data-id='${r.id}'>Remove</button></td></tr>`);
if(page==='imsda-reg-checkin') app.html('<p>QR Scanner <video id="v" width="320" height="240" autoplay playsinline></video><button class="button" id="start">Start Camera</button><button class="button" id="stop">Stop Camera</button></p><script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"><\/script>');
if(page==='imsda-reg-rosters') renderGeneric('getChurchRosters',['Church','Name','Arrival','Departure','Payment','Checked In'],r=>`<tr><td>${r.church||''}</td><td>${r.name||''}</td><td>${r.arrival||''}</td><td>${r.departure||''}</td><td>${r.paymentStatus||''}</td><td>${r.checkedIn?'Yes':'No'}</td></tr>`);
if(page==='imsda-reg-promo') renderGeneric('getPromoCodes',['Code','Description','Discount','Min Purchase','Uses','Expiry','Active','Delete'],r=>`<tr><td>${r.code||''}</td><td>${r.description||''}</td><td>${r.discount||''}</td><td>${r.minPurchase||''}</td><td>${r.uses||''}</td><td>${r.expiry||''}</td><td>${r.active?'Yes':'No'}</td><td><button class='button dp' data-code='${r.code}'>Delete</button></td></tr>`);
});
</script>
<?php }
}
