<?php
if (!defined('ABSPATH')) { exit; }
class IMSDA_Reg_Parser {
    private static function resolve($raw,$map,$key){ foreach((array)($map[$key]??[]) as $cand){ if(isset($raw[$cand]) && $raw[$cand]!=='' && $raw[$cand]!==null){ $v=$raw[$cand]; if(is_array($v)){ if(isset($v['first_name'])) return sanitize_text_field($v['first_name']); if(isset($v['last_name'])) return sanitize_text_field($v['last_name']); continue; } return sanitize_text_field($v);} } return ''; }
    public static function parse($entry_id,$event){ global $wpdb; $sub=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$wpdb->prefix}fluentform_submissions WHERE id=%d",intval($entry_id)),ARRAY_A); if(!$sub) return []; $raw=json_decode($sub['response'],true); $raw=is_array($raw)?$raw:[]; $map=is_array($event->field_map ?? null)?$event->field_map:IMSDA_Reg_Event_Registry::default_field_map();
    $church=self::resolve($raw,$map,'church'); if($church==='Other' && !empty($raw['church_other'])) $church=sanitize_text_field($raw['church_other']);
    $pm=strtolower(self::resolve($raw,$map,'payment_method')); if(in_array($pm,['offline','pay_later','later'],true))$pm='pay_later'; elseif(in_array($pm,['square','card','credit'],true))$pm='square'; elseif(!in_array($pm,['check','cash'],true)) $pm=$event->payment_default ?? 'pay_later';
    $promo=strtoupper(sanitize_text_field(self::resolve($raw,$map,'promo_code'))); $amount=0.0; $meta=$wpdb->get_var($wpdb->prepare("SELECT value FROM {$wpdb->prefix}fluentform_submission_meta WHERE submission_id=%d AND meta_key='_payment_entries' ORDER BY id DESC LIMIT 1",intval($entry_id))); if($meta){$m=json_decode($meta,true);$a=$m['amount']??($m[0]['amount']??0);$amount=floatval($a)/100;} if($amount<=0){foreach(['total','payment_total','registration_total','amount','final_amount','calculated_total','order_total'] as $k){$v=$raw[$k]??'';$v=is_array($v)?'':str_replace(['$',','],'',(string)$v); if(is_numeric($v)){ $amount=floatval($v); break;}}}
    $attendees=[]; $count=max(1,min(5,intval(self::resolve($raw,$map,'attendee_count')?:1))); if(!empty($event->feature_attendees)){ for($n=1;$n<=$count;$n++){ $p='a'.$n.'_'; $fn=$n===1?self::resolve($raw,$map,'first_name'):sanitize_text_field($raw[$p.'first_name']??''); if(!$fn) continue; $ln=$n===1?self::resolve($raw,$map,'last_name'):sanitize_text_field($raw[$p.'last_name']??''); $attendees[]=['first_name'=>$fn,'last_name'=>$ln,'meal_preference'=>sanitize_text_field($raw[$p.'meal_preference']??''),'dietary_needs'=>sanitize_text_field($raw[$p.'dietary_needs']??''),'childcare_needed'=>sanitize_text_field($raw[$p.'childcare_needed']??''),'seminar_preferences'=>['session_1'=>['pref_1'=>sanitize_text_field($raw[$p.'session1_pref1']??''),'pref_2'=>sanitize_text_field($raw[$p.'session1_pref2']??'')],'session_2'=>['pref_1'=>sanitize_text_field($raw[$p.'session2_pref1']??''),'pref_2'=>sanitize_text_field($raw[$p.'session2_pref2']??'')]]]; }} else {$attendees[]=['first_name'=>self::resolve($raw,$map,'first_name'),'last_name'=>self::resolve($raw,$map,'last_name')];}
    return ['entry_id'=>intval($sub['id']),'form_id'=>intval($sub['form_id']),'first_name'=>self::resolve($raw,$map,'first_name'),'last_name'=>self::resolve($raw,$map,'last_name'),'email'=>sanitize_email(self::resolve($raw,$map,'email')),'phone'=>self::resolve($raw,$map,'phone'),'church'=>$church,'arrival_date'=>self::resolve($raw,$map,'arrival_date'),'departure_date'=>self::resolve($raw,$map,'departure_date'),'dietary_needs'=>self::resolve($raw,$map,'dietary_needs'),'emergency_contact_name'=>self::resolve($raw,$map,'emergency_contact_name'),'emergency_contact_phone'=>self::resolve($raw,$map,'emergency_contact_phone'),'special_needs'=>self::resolve($raw,$map,'special_needs'),'promo_code'=>$promo,'payment_method'=>$pm,'amount'=>$amount,'ip_address'=>sanitize_text_field($sub['ip']??''),'submitted_at'=>sanitize_text_field($sub['created_at']??''),'attendees'=>$attendees,'attendee_count'=>count($attendees),'worker_flag'=>sanitize_text_field($raw['worker_flag']??'')]; }
}
