function rowToObject(r){return {registrationId:r[0],timestamp:r[1],firstName:r[2],lastName:r[3],email:r[4],phone:r[5],church:r[6],housingOption:r[7],arrivalDate:r[8],departureDate:r[9],dietaryNeeds:r[10],emergencyContactName:r[11],emergencyContactPhone:r[12],specialNeeds:r[13],promoCode:r[14],discountAmount:Number(r[15]||0),originalAmount:Number(r[16]||0),finalAmount:Number(r[17]||0),paymentMethod:r[18],paymentStatus:r[19],squarePaymentId:r[20],ffEntryId:r[21],status:r[22],transferNotes:r[23],checkedIn:r[24],checkInTime:r[25],checkInBy:r[26],qrToken:r[27],editToken:r[28],adminNotes:r[29]};}
function writeRegistration(d){try{getSS().getSheetByName('Registrations').appendRow([d.registrationId,new Date(),d.firstName,d.lastName,d.email,d.phone,d.church,d.housingOption,d.arrivalDate,d.departureDate,d.dietaryNeeds,d.emergencyContactName,d.emergencyContactPhone,d.specialNeeds,d.promoCode,d.discountAmount,d.originalAmount,d.finalAmount,d.paymentMethod,d.paymentStatus,d.squarePaymentId,d.ffEntryId,d.status||'active',d.transferNotes||'',d.checkedIn||false,d.checkInTime||'',d.checkInBy||'',d.qrToken,d.editToken,d.adminNotes||'']);return {success:true};}catch(e){return {success:false,message:e.message};}}
function getRegistrationById(id){var s=getSS().getSheetByName('Registrations');var v=s.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][0])===String(id))return rowToObject(v[i]);return null;}
function getRegistrationByEditToken(t){var s=getSS().getSheetByName('Registrations');var v=s.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][28])===String(t))return rowToObject(v[i]);return null;}
function getRegistrationByQRToken(t){var s=getSS().getSheetByName('Registrations');var v=s.getDataRange().getValues();for(var i=1;i<v.length;i++)if(String(v[i][27])===String(t))return {row:i+1,data:rowToObject(v[i])};return null;}
function updateRegistration(id,fields){try{var s=getSS().getSheetByName('Registrations');var v=s.getDataRange().getValues();var map={firstName:3,lastName:4,email:5,phone:6,church:7,housingOption:8,arrivalDate:9,departureDate:10,dietaryNeeds:11,emergencyContactName:12,emergencyContactPhone:13,specialNeeds:14,status:23,transferNotes:24,checkedIn:25,checkInTime:26,checkInBy:27,adminNotes:30};for(var i=1;i<v.length;i++){if(String(v[i][0])===String(id)){Object.keys(fields||{}).forEach(function(k){if(map[k])s.getRange(i+1,map[k]).setValue(fields[k]);});return {success:true};}}return {success:false,message:'Registration not found'};}catch(e){return {success:false,message:e.message};}}
function getAllRegistrations(filters){var s=getSS().getSheetByName('Registrations');var rows=s.getDataRange().getValues().slice(1).map(rowToObject);return rows.filter(function(r){if(filters&&filters.status&&r.status!==filters.status)return false;var q=(filters&&filters.search?String(filters.search).toLowerCase():'');if(q && [r.firstName,r.lastName,r.email,r.church].join(' ').toLowerCase().indexOf(q)===-1)return false;return true;});}
function searchRegistrations(q){q=String(q||'').toLowerCase();return getAllRegistrations({}).filter(function(r){return [r.firstName,r.lastName,r.email,r.church].join(' ').toLowerCase().indexOf(q)>-1;}).slice(0,20);}
function getChurchRosters(){var groups={};getAllRegistrations({status:'active'}).forEach(function(r){var c=r.church||'Unspecified';if(!groups[c])groups[c]=[];groups[c].push(r);});return Object.keys(groups).sort().map(function(c){return {name:c,members:groups[c]};});}
